default:
  jetty_port: 8983
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"
staging:
  jetty_port: 8987
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"
production:
  jetty_port: 8987
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"
